server:
  port: 8080

database:
  url: jdbc:h2:mem:expense-manager
  username: sa
  password: password
  driver: org.h2.Driver

spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:expense-manager
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect